.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GTS\-CACHE" "1" "October 2020" "" ""
.
.SH "NAME"
\fBgts\-cache\fR \- manage gts cache files
.
.SH "SYNOPSIS"
usage: gts cache [\-\-version] [\-h | \-\-help] \fIcommand\fR [\fIargs\fR]
.
.SH "DESCRIPTION"
\fBgts\-cache\fR is a command set for interacting with gts\-cache(7) files\. For all detailed description of how gts(1) handles caches, refer to gts\-cache(7)\.
.
.SH "COMMANDS"
.
.TP
\fBgts\-cache\-list(1)\fR
List the cache files\.
.
.TP
\fBgts\-cache\-path(1)\fR
Print the cache directory path\.
.
.TP
\fBgts\-cache\-purge(1)\fR
Delete all cache files\.
.
.SH "BUGS"
\fBgts\-cache\fR currently has no known bugs\.
.
.SH "AUTHORS"
\fBgts\-cache\fR is written and maintained by Kotone Itaya\.
.
.SH "SEE ALSO"
gts(1), gts\-cache\-list(1), gts\-cache\-path(1), gts\-cache\-purge(1), gts\-cache(7)
