.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GTS\-SEQOUT" "7" "October 2020" "" ""
.
.SH "NAME"
\fBgts\-seqout\fR \- output sequence formats supported in GTS\.
.
.SH "SYNOPSIS"
.
.IP "\(bu" 4
\fBGenBank\fR
.
.IP "\(bu" 4
\fBFASTA\fR
.
.IP "" 0
.
.SH "DESCRIPTION"
GTS implements parsers for a number of sequence formats, and have plans for implementing more commonly used sequence formats\.
.
.SH "SEE ALSO"
gts(1), gts\-seqin(7)
