.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GTS\-ROTATE" "1" "October 2020" "" ""
.
.SH "NAME"
\fBgts\-rotate\fR \- shift the coordinates of a circular sequence
.
.SH "SYNOPSIS"
gts\-rotate [\-\-version] [\-h | \-\-help] [\fIargs\fR] \fIamount\fR \fIseqin\fR
.
.SH "DESCRIPTION"
\fBgts\-rotate\fR takes a single sequence input and shifts the sequence so that the position matching the location specified by the given \fBlocator\fR comes to the start of the sequence file\. A locator is a combination of one of \fBpoint location\fR, \fBrange location\fR, or \fBselector\fR, and a \fBmodifier\fR in the form \fB[selector|point|range][@modifier]\fR\. See gts\-locator(7) for a more in\-depth explanation of a locator\. Refer to the EXAMPLES for some examples to get started\.
.
.P
The topology of a sequence that is rotated will be changed to circular\.
.
.SH "OPTIONS"
.
.TP
\fB<locator>\fR
A locator string ([selector|point|range][@modifier])\.
.
.TP
\fB<seqin>\fR
Input sequence file (may be omitted if standard input is provided)\. See gts\-seqin(7) for a list of currently supported list of sequence formats\.
.
.TP
\fB\-F <format>\fR, \fB\-\-format=<format>\fR
Output file format (defaults to same as input)\. See gts\-seqout(7) for a list of currently supported list of sequence formats\. The format specified with this option will override the file type detection from the output filename\.
.
.TP
\fB\-o <output>\fR, \fB\-\-output=<output>\fR
Output sequence file (specifying \fB\-\fR will force standard output)\. The output file format will be automatically detected from the filename if none is specified with the \fB\-F\fR or \fB\-\-format\fR option\.
.
.SH "EXAMPLES"
Rotate a sequence 100 bases:
.
.IP "" 4
.
.nf

$ gts rotate 100 <seqin>
.
.fi
.
.IP "" 0
.
.P
Rotate a sequence to the first CDS in the sequence:
.
.IP "" 4
.
.nf

$ gts rotate CDS <seqin>
.
.fi
.
.IP "" 0
.
.SH "BUGS"
\fBgts\-rotate\fR currently has no known bugs\.
.
.SH "AUTHORS"
\fBgts\-rotate\fR is written and maintained by Kotone Itaya\.
.
.SH "SEE ALSO"
gts(1), gts\-locator(7), gts\-modifier(7), gts\-selector(7), gts\-seqin(7), gts\-seqout(7)
