.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GTS\-CACHE\-LIST" "1" "October 2020" "" ""
.
.SH "NAME"
\fBgts\-cache\-list\fR \- list the cache files
.
.SH "SYNOPSIS"
gts\-cache\-list [\-\-version] [\-h | \-\-help]
.
.SH "DESCRIPTION"
\fBgts\-cache\-list\fR will print a list of existing gts\-cache(7) files, along with its file size and the total size occupied by the files\.
.
.SH "OPTIONS"
None\.
.
.SH "BUGS"
\fBgts\-cache\-list\fR currently has no known bugs\.
.
.SH "AUTHORS"
\fBgts\-cache\-list\fR is written and maintained by Kotone Itaya\.
.
.SH "SEE ALSO"
gts(1), gts\-cache(1), gts\-cache\-path(1), gts\-cache\-purge(1), gts\-cache(7)
