.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GTS\-DEFINE" "1" "October 2020" "" ""
.
.SH "NAME"
\fBgts\-define\fR \- define a new feature
.
.SH "SYNOPSIS"
gts\-define [\-\-version] [\-h | \-\-help] [\fIargs\fR] \fIkey\fR \fIlocation\fR \fIseqin\fR
.
.SH "DESCRIPTION"
Define a new feature\.
.
.SH "OPTIONS"
.
.TP
\fB<key>\fR
Feature key\.
.
.TP
\fB<location>\fR
Feature location\.
.
.TP
\fB<seqin>\fR
Input sequence file (may be omitted if standard input is provided)\.
.
.TP
\fB\-F <format>\fR, \fB\-\-format=<format>\fR
Output file format (defaults to same as input)\.
.
.TP
\fB\-o <output>\fR, \fB\-\-output=<output>\fR
Output sequence file (specifying \fB\-\fR will force standard output)\.
.
.TP
\fB\-q <qualifier>\fR, \fB\-\-qualifier=<qualifier>\fR
Qualifier key\-value pairs (syntax: key=value))\.
.
.SH "BUGS"
\fBgts\-define\fR currently has no known bugs\.
.
.SH "AUTHORS"
\fBgts\-define\fR is written and maintained by @AUTHOR@\.
.
.SH "SEE ALSO"

