before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/gts
    id: "gts-bio"
    env:
      - CGO_ENABLED=0
    binary: gts
    flags: -v
    goos:
      - linux
      - darwin
  - main: ./cmd/togo
    id: "gts-togo"
    env:
      - CGO_ENABLED=0
    binary: togo
    flags: -v
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
        - README.md
        - LICENSE
        - manpage/*.1
        - manpage/*.7
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - id: gts-bio-nfpms
    builds:
      - gts-bio
      - gts-togo
    homepage: https://github.com/go-gts/gts
    maintainer: Kotone Itaya <kotone [at] sfc.keio.ac.jp>
    description: "GTS: Genome Transformation Subprograms"
    license: MIT
    formats:
      - deb
      - rpm
    files:
        "./manpage/gts*.1": "/usr/share/man/man1"
        "./manpage/gts*.7": "/usr/share/man/man7"
    epoch: 1
brews:
  - name: gts-bio
    tap:
      owner: go-gts
      name: homebrew-gts
    folder: Formula
    homepage: https://github.com/go-gts/gts
    description: "GTS: Genome Transformation Subprograms"
    dependencies:
      - name: make
        type: build
    install: |
        bin.install "gts"
        bin.install "togo"
        man1.install Dir["manpage/gts*.1"]
        man7.install Dir["manpage/gts*.7"]
    test: system "#{bin}/gts --version"
