before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/gts
    id: "gts-bio"
    env:
      - CGO_ENABLED=0
    binary: gts
    flags: -v
    goos:
      - linux
      - darwin
  - main: ./cmd/togo
    id: "gts-togo"
    env:
      - CGO_ENABLED=0
    binary: togo
    flags: -v
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - id: gts-bio-nfpms
    builds:
      - gts-bio
      - gts-togo
    homepage: https://github.com/go-gts/gts
    maintainer: Kotone Itaya <kotone [at] sfc.keio.ac.jp>
    description: "GTS: the Genomics Tools Suite"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
brews:
  - name: gts-bio
    github:
      owner: go-gts
      name: homebrew-gts
    homepage: https://github.com/go-gts/gts
    description: "GTS: the Genomics Tools Suite"
    dependencies:
      - name: go
        type: build
    test: system "#{bin}/gts --version"
