{% set version = "0.26.7" %}

package:
    name: gts-bio
    version: {{ version }}

source:
    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Darwin_x86_64.tar.gz # [osx]
    sha256: a02680ceb0e01428f03e2622db12edcd476a991b05c3549f666cb6c3b82d32c2 # [osx]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_x86_64.tar.gz # [linux64]
    sha256: 217ed40cdb91e860b52836d97ea1748ca484a6fc493e2c8ba9c70e5ac8156b89 # [linux64]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_i386.tar.gz # [linux32]
    sha256: 0633826f654d583c898361c638db7576d79802fdec875fbe82850b588648bcad # [linux32]

build:
    number: 0
    skip: False

test:
    commands:
        - gts --version
        - togo --version

about:
    home: https://github.com/go-gts/gts
    summary: Genome Transformation Subprograms
    license: MIT

extra:
    skip-lints:
        - should_be_noarch_generic
        - should_not_be_noarch_source
