{% set version = "0.26.5" %}

package:
    name: gts-bio
    version: {{ version }}

source:
    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Darwin_x86_64.tar.gz # [osx]
    sha256: d2e54588c35c9c079d2016064155ce74b48dfcb2239c443d46822f14c05e2d29 # [osx]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_x86_64.tar.gz # [linux64]
    sha256: 4495d9d957f4fb9dd70120569abe0cf3599cb3d6b6a5f1c76f848321ff63439a # [linux64]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_i386.tar.gz # [linux32]
    sha256: e7f28c2b2c1f099950f0dec2f13728d1d29a32aa926de823405cf1729723856f # [linux32]

build:
    number: 0
    skip: False

test:
    commands:
        - gts --version
        - togo --version

about:
    home: https://github.com/go-gts/gts
    summary: Genome Transformation Subprograms
    license: MIT

extra:
    skip-lints:
        - should_be_noarch_generic
        - should_not_be_noarch_source
