{% set version = "0.23.1" %}

package:
    name: gts-bio
    version: {{ version }}

source:
    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Darwin_x86_64.tar.gz # [osx]
    sha256: 412b2fe7f870bc4c08edf0f8004182490a33be9d7ec037dcd5e42ec7e69f8642 # [osx]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_x86_64.tar.gz # [linux64]
    sha256: fd828dd2474145497a1f8076255ef312cf227691762219027e5595eea9d68674 # [linux64]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_i386.tar.gz # [linux32]
    sha256: 9444ab67ad02a6531fea9eb8dba1e95cfb91dae905b07fa55346d695180ab5dc # [linux32]

build:
    number: 0
    skip: False

test:
    commands:
        - gts --version
        - togo --version

about:
    home: https://github.com/go-gts/gts
    summary: Genome Transformation Subprograms
    license: MIT

extra:
    skip-lints:
        - should_be_noarch_generic
        - should_not_be_noarch_source
