{% set version = "0.26.3" %}

package:
    name: gts-bio
    version: {{ version }}

source:
    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Darwin_x86_64.tar.gz # [osx]
    sha256: 20362cbf1e0d9c0ad1e5ee8967298a319bc0f07690e6dad87d1fb197464396b3 # [osx]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_x86_64.tar.gz # [linux64]
    sha256: 66217e8c96bfb6d1dab3df2fb8d2af9cd26dccfce3fbe642b98c64ac7ef9e280 # [linux64]

    url: https://github.com/go-gts/gts/releases/download/v{{ version }}/gts_{{ version }}_Linux_i386.tar.gz # [linux32]
    sha256: 8a641984511f81071083dcad83e80e807710f47e75b23fa9eefa4a850a5c7c27 # [linux32]

build:
    number: 0
    skip: False

test:
    commands:
        - gts --version
        - togo --version

about:
    home: https://github.com/go-gts/gts
    summary: Genome Transformation Subprograms
    license: MIT

extra:
    skip-lints:
        - should_be_noarch_generic
        - should_not_be_noarch_source
